# Generated by Django 5.1.3 on 2024-11-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedSite',
            fields=[
                ('archive_id', models.AutoField(primary_key=True, serialize=False)),
                ('archive_url', models.TextField()),
                ('archive_content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
